In [177]:
# Dependencies
import os
import pandas as pd

In [178]:
# Create csv_path variable
csv_path = os.path.join('HeroesOfPymoli','Resources', 'purchase_data.csv')

# Read with pandas
purchase_frame = pd.read_csv(csv_path)
purchase_frame.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [179]:
### Player Count
# Total Number of Unique Playes
player_count = len(purchase_frame['SN'].unique())
player_count

576

In [180]:
### Purchasing Analysis
# Number of Unique Items
unique_items = len(purchase_frame['Item Name'].unique())
# Average Price
avg_price = round(purchase_frame['Price'].mean(), 2)
# Total Number of Purchases
purchase_total = len(purchase_frame)
# Total Revenue
total_revenue = round(purchase_frame['Price'].sum(), 2)
purchase_analysis = pd.DataFrame({"Unique Items": [unique_items],
                                  "Average Price": f"${avg_price}",
                                  "Total Purchases": [purchase_total],
                                  "Total Revenue": f"${total_revenue}"})
purchase_analysis

   Unique Items Average Price  Total Purchases Total Revenue
0           179         $3.05              780      $2379.77

In [181]:
### Gender Demographics
# Male Count 
gender_list = purchase_frame['Gender'].unique()
gender_list

array(['Male', 'Other / Non-Disclosed', 'Female'], dtype=object)

In [182]:
index_list = []
columns = ['Total Count', 'Percentage of Players']
data = []
for gender in gender_list:
    tempframe = purchase_frame.loc[purchase_frame['Gender'] == gender]
    data.append([len(tempframe['SN'].unique()),f"{round(len(tempframe['SN'].unique())/player_count * 100,2)}%"])
    index_list.append(gender)
gender_demo = pd.DataFrame(columns=columns,data=data)    
gender_demo.index = index_list
gender_demo.sort_values(by='Total Count', ascending=False, inplace=True)
gender_demo

                       Total Count Percentage of Players
Male                           484                84.03%
Female                          81                14.06%
Other / Non-Disclosed           11                 1.91%

In [183]:
def purchasing_analysis(df, index_list, ref_col)
    columns = ["Purchase Count", "Average Purchase Price", "Total Purchase                              Value", "Avg Total Purchase per Person"]
    data = []
    for index in index_list:
        tempframe = df.loc[df[ref_col] = index]
        purchase_count = len(tempframe)
        avg_price = round(tempframe['Price'].mean(),2)
        total_value = round(tempframe['Price'].sum(),2)
        total_players = tempframe['SN'].unique()
        avg_total = round(total_value/total_players,2)
        data.append([purchase_count,f"${avg_price}",f"{}"])

In [184]:
gender_breakdown = pd.DataFrame()
for gender in gender_list:
    tempframe = purchase_frame.loc[purchase_frame['Gender'] == gender]
    gender_breakdown = analysis(tempframe)
    print(gender_breakdown)

None
None
None

In [185]:
# Print out max age and min age from dataset to create correct age groups
ages = purchase_frame['Age'].unique()
print(f"Max Age: {max(ages)}, Min Age: {min(ages)}")

Max Age: 45, Min Age: 7

In [186]:
### Age Demographics
# Age ranges 
labels = ['<10','10-14','15-19','20-24','25-29','30-34','35-39','40+']
bins = ['0','9','14','15','19','20','24','25','29','30','34','35','39','40','45']

In [187]:
# For refernce
purchase_frame.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [188]:
### Top Spenders
# Group dataframe by SN and drop everything but Price
grouped_frame = pd.DataFrame()
grouped_frame = purchase_frame.groupby(['SN'], as_index=False).sum().sort_values(['Price'], ascending=False)
top_five = grouped_frame.head(5)
players = top_five['SN'].unique()
topfive_output = dict()
i = 1
for player in players: 
    tempdict = dict()
    tempframe = purchase_frame.loc[purchase_frame['SN'] == player]
    purchase_count = len(tempframe)
    avg_price = tempframe['Price'].mean()
    total_value = tempframe['Price'].sum()
    tempdict['SN'] = player
    tempdict['Purchase Count'] = purchase_count
    tempdict['Average Purchase Price'] = round(avg_price, 2)
    tempdict['Total Purchase Value'] = round(total_value, 2)
    topfive_output[i] = tempdict
    i = i+1
topfive_output

{1: {'SN': 'Lisosia93',
  'Purchase Count': 5,
  'Average Purchase Price': 3.79,
  'Total Purchase Value': 18.96},
 2: {'SN': 'Idastidru52',
  'Purchase Count': 4,
  'Average Purchase Price': 3.86,
  'Total Purchase Value': 15.45},
 3: {'SN': 'Chamjask73',
  'Purchase Count': 3,
  'Average Purchase Price': 4.61,
  'Total Purchase Value': 13.83},
 4: {'SN': 'Iral74',
  'Purchase Count': 4,
  'Average Purchase Price': 3.4,
  'Total Purchase Value': 13.62},
 5: {'SN': 'Iskadarya95',
  'Purchase Count': 3,
  'Average Purchase Price': 4.37,
  'Total Purchase Value': 13.1}}

In [189]:
### Most Popular Items
grouped_frame = purchase_frame.groupby(['Item ID'], as_index=False).size().sort_values([1], ascending=False)
grouped_frame

KeyError: 1